version: '3'

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pSQL123"
      POSTGRES_USER: "psql"
      POSTGRES_DB: "news-db"
    restart: always
  news-app:
    image: drennout/news-app:1.0.0
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: "jdbc:postgresql://db:5432/news-db"
      DATASOURCE_USERNAME: "psql"
      DATASOURCE_PASSWORD: "pSQL123"
    depends_on:
      - db