version: '3'

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pSQL123"
      POSTGRES_USER: "psql"
      POSTGRES_DB: "news-db"
    restart: always