spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news-db
    username: psql
    password: pSQL123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop