spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/news-db}
    username: ${DATASOURCE_USERNAME:psql}
    password: ${DATASOURCE_PASSWORD:pSQL123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  boot:
    admin:
      client:
        url: http://localhost:8081